### ISSUE TITLE
One should display error messages when dataset load fails for some reason

### ISSUE THREAD

**Issue by FrancescAlted** [ironArray/Caterva2#104]
For example, a when opening a persistent lazyexpr where one of its operands is not available, a message like:

```
python -c "import blosc2; c=blosc2.open('_caterva2/sub/personal/d00f76bf-d05d-45a6-981b-81b1862ee9d4/proves-b2nd/d2.b2nd'); print(c.info)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/faltet/blosc/python-blosc2/src/blosc2/schunk.py", line 1488, in open
    return blosc2._open_lazyarray(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/faltet/blosc/python-blosc2/src/blosc2/lazyexpr.py", line 2130, in _open_lazyarray
    op = blosc2.open(value)
         ^^^^^^^^^^^^^^^^^^
  File "/Users/faltet/blosc/python-blosc2/src/blosc2/schunk.py", line 1471, in open
    raise FileNotFoundError(f"No such file or directory: {urlpath}")
FileNotFoundError: No such file or directory: /Users/faltet/blosc/Caterva2/state/subscriber/shared/ds-3d.b2nd
```

should be captured and displayed.

**Comment by FrancescAlted** [comment]
This has been addressed in main.  In case more details are needed, we can further refine the messages.
